[features]
seeds = false
skip-lint = false
[programs.localnet]
flash_swap = "JUPLdTqUdKztWJ1isGMV92W2QvmEmzs9WTJjhZe4QdJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/siong/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
